


try:
    a=sum(4)
except Exception as e:
    print("errorHeheheh:", e)
